### ISSUE TITLE
vaadin app does not response

### ISSUE THREAD

**Issue by klaushauschild1984** [appreciated/maven-springboot-electron#9]
Playing around with vaadin and managing to get your templat running on my linux setup I noticed the application does not respond to anything.
Opening the app in browser via `localhost:8080` shows a message _Cookies deactivated..._
This message disappears and the app is back to working as expected when opened via `127.0.0.1:8080`.
Is this a thing or just a symptom at my local machine?

**Comment by klaushauschild1984** [comment]
Seam to be a bug / problem in Vaadin. After updating Vaadin version to `15.0.2` like in https://github.com/appreciated/maven-springboot-electron/pull/3 it works as intended.

**Comment by appreciated** [comment]
This issue sounds weird 🤔 I guess some investigation needs to be done here.
